# For save directories only enter the parent directory for all projects checkpoints. 
# project.name will be joined to both checkpoints and runs as the basename directory.

project:
    name:             'face_na_seed'
    description:      'Training VGG on VGG16 without Asian faces'
    model:            'VGG16'
data_directories:
    task1:            '/om2/group/nklab/shared/datasets/data_facecar_na'
save_directories:
    checkpoints_dir:  '/mindhive/nklab4/users/juliom/projects/FaceNets/checkpoints2/vgg/'
    log_dir:          '/mindhive/nklab4/users/juliom/projects/FaceNets/runs2/vgg/'
saving:
    keep:             [-1]
    function:         'step'
    params:           {'step': 10, 'offset': 0}
    max_count:        200
hyperparameters: 
    batch_size:       128
    optimizer:        'sgd'
    momentum:         0.9
    learning_rate:    0.001
    use_scheduler:    True
    scheduler:        'ReduceLROnPlateau'
    scheduler_params: {'patience': 5, 'verbose': True}
    weight_decay:     0.0001
    split:            False
max_train_samples:
    task1:            100
max_valid_samples:
    task1:            5