project:
    name:             'face_inanimate_nofood_fc_small_subnet'
    description:      'Fine Tuning'
    model:            'VGG16SubNetwork'
data_directories:
    task1:            '/mindhive/nklab4/shared/datasets/data_facecar'
    task2:            '/mindhive/nklab4/shared/datasets/data_inanimate_nofood'
save_directories:
    checkpoints_dir:  '/mindhive/nklab4/users/juliom/projects/FaceNets/checkpoints/subnet'
    log_dir:          '/mindhive/nklab4/users/juliom/projects/FaceNets/runs/subnet'
hyperparameters:  
    optimizer:        'sgd'
    batch_size:       64
    learning_rate:    0.01
    momentum:         0.9
    step_size:        100
    weight_decay:     0.0
    split:            False
max_train_samples:
    task1:            53
    task2:            231
max_valid_samples:
    task1:            6
    task2:            26