# For save directories only enter the parent directory for all projects checkpoints. 
# project.name will be joined to both checkpoints and runs as the basename directory.

project:
    name:             '11_meg_alexnet'
    description:      'Training AlexNet on 8 faces from MEG experiment.'
    model:            'AlexNet'
data_directories:
    task1:            '/mindhive/nklab4/users/joanneyu/split_runs/run1/01'
save_directories:
    checkpoints_dir:  '/mindhive/nklab4/users/juliom/projects/FaceNets/checkpoints/alexnet'
    log_dir:          '/mindhive/nklab4/users/juliom/projects/FaceNets/runs/alexnet'
hyperparameters: 
    optimizer:        'adam'
    batch_size:       64
    learning_rate:    0.0001
    momentum:         None
    step_size:        40
    weight_decay:     0.0
    split:            False
max_train_samples:
    task1:            200
max_valid_samples:
    task1:            14
