# For save directories only enter the parent directory for all projects checkpoints. 
# project.name will be joined to both checkpoints and runs as the basename directory.

project:
    name:             'face_400k_nobatchnorm'
    description:      'Training AlexNet using SGD on faces on single classifier with 400k samples.'
    model:            'AlexNetNoBatchnorm'
data_directories:
    task1:            '/mindhive/nklab4/shared/datasets/data_facecar'
save_directories:
    checkpoints_dir:  '/mindhive/nklab4/users/juliom/projects/FaceNets/checkpoints2/alexnet/'
    log_dir:          '/mindhive/nklab4/users/juliom/projects/FaceNets/runs2/alexnet/'
saving:
    keep:             [15]
    function:         'step'
    params:           {'step': 5, 'offset': 0}
    max_count:        5
hyperparameters: 
    batch_size:       128
    optimizer:        'sgd'
    momentum:         0.9
    learning_rate:    0.001
    use_scheduler:    True
    scheduler:        'ReduceLROnPlateau'
    scheduler_params: {'patience': 5, 'verbose': True}
    weight_decay:     0.0001
    split:            False
max_train_samples:
    task1:            247
max_valid_samples:
    task1:            13