# For save directories only enter the parent directory for all projects checkpoints. 
# project.name will be joined to both checkpoints and runs as the basename directory.

project:
    name:             'cars_seed'
    description:      'Training VGG on cars.'
    model:            'VGG16'
data_directories:
    task1:            '/mindhive/nklab4/shared/datasets/data_car'
save_directories:
    checkpoints_dir:  '/mindhive/nklab4/users/juliom/projects/FaceNets/checkpoints2/vgg/'
    log_dir:          '/mindhive/nklab4/users/juliom/projects/FaceNets/runs2/vgg/'
saving:
    keep:             [-1]
    function:         'step'
    params:           {'step': 10, 'offset': 0}
    max_count:        100
hyperparameters: 
    batch_size:       128
    optimizer:        'sgd'
    momentum:         0.9
    learning_rate:    0.001
    use_scheduler:    True
    scheduler:        'ReduceLROnPlateau'
    scheduler_params: {'patience': 10, 'verbose': True}
    weight_decay:     0.0001
    split:            False
max_train_samples:
    task1:            45
max_valid_samples:
    task1:            5