# For save directories only enter the parent directory for all projects checkpoints. 
# project.name will be joined to both checkpoints and runs as the basename directory.

project:
    name:             'face_400k_transfer_freeze_car'
    description:      'Transfer Learning on VGG faces to cars'
    model:            'VGG16'
data_directories:
    task1:            '/mindhive/nklab4/shared/datasets/data_facecar'
save_directories:
    checkpoints_dir:  '/mindhive/nklab4/users/juliom/projects/FaceNets/checkpoints2/vgg/'
    log_dir:          '/mindhive/nklab4/users/juliom/projects/FaceNets/runs2/vgg/'
hyperparameters: 
    optimizer:        'sgd'
    batch_size:       128
    learning_rate:    0.001
    momentum:         0.9
    step_size:        50
    weight_decay:     0.0001
    split:            False
max_train_samples:
    task1:            45
max_valid_samples:
    task1:            5